### ISSUE TITLE
Line definition creates wrong lines in multiview

### ISSUE THREAD

**Issue by dandad36** [LetsConstructIT/Grasshopper-TeklaDrawingLink#27]
I created lines for multiple views using line definition. With 1 view it's ok but multiview has a problem. The lines are at the wrong locations.  Sometimes it's wrong number of lines too?
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/2da437a4-d2bf-45d9-9c7c-7ca1f51ead28)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/6ee9edbe-35ba-4047-a4e4-eb03c916624c)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/41262390/5ad0cbe6-f8dc-4bf2-9504-8cdfccbcc498)

**Comment by olszewski-grzegorz** [comment]
Hi! Please provide View input as a list, not a tree. All of the insertion components are following the multi-view convention (unwritten, I know, I will tell about it during the Workshop). You have meet the situation when this component was evaluated twice (due to providing view as a tree).

Multi-view convention states: 
- provide views as list, index of those views is the beacon for the next inputs
- analyze other inputs as a tree, get the longest one (with the highest number of branches) and link it with the expected view based on the first path indice

That is the structure you need:
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/63e987cf-7509-4fbf-8f52-40148e6b455a)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/9f29c50d-8cd6-4d47-ae47-db1c6e2e8d4d)


You don't want such an input:
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/19dc64b0-6e69-4f61-b821-dfc9a1113892)
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/5408d7a0-0e87-459f-bf4d-944fafb43303)

**Comment by dandad36** [comment]
Thank you for the quick answer. I think it'd be helpful to add this in the tooltips of the definition too. I'll be looking forward to your Workshop :)
