### ISSUE TITLE
Loop example

### ISSUE THREAD

**Issue by Mantsi** [LetsConstructIT/Grasshopper-TeklaDrawingLink#37]
Hello. Could you shed more light on the loop component and how it could be used? 

Again, thanks for the continuous updates on this tool! Very much appreciated!

![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/165034583/6aab0dd2-47fc-493c-9e74-71aebe399f73)

**Comment by olszewski-grzegorz** [comment]
Hi @Mantsi ! This is a foreach loop. For an input list of objects, it will recalculate the components between the beginning of the loop and the end of the loop with subsequent elements from the list.

Typical usecase for this are the operations over multiple drawings. You can't do it in parallel, with a single flow due to Tekla limitations to having only one drawing opened at a time.

But, it's better to start with something simplier, like this:
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/31b46c0f-443b-4e97-b95b-84e5d7e1237d)
Of course, for this you don't need a loop, but the essence is nicecly captured in this screenshot. Please look that Multipllication component is seen as run only once, but the type of input suggest that it is not possible (you see single wire = one object as input).

For the Tekla drawing operations, let's do something like this:
![image](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/assets/24588349/abc59e50-6e30-4a76-bfc6-4775fab3cec1)
This script will operate on drawings selected in the document manager. It opens drawings sequentially and moves all of the views by the fixed vector.

You can try with those components based on the script:
[samples/Samples.gh](https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/blob/000e528f7a1bed16733248b2d3e90d6cf023e105/samples/Samples.gh)
