### ISSUE TITLE
Only Rhino 8

### ISSUE THREAD

**Issue by TautvydasBakas** [LetsConstructIT/Grasshopper-TeklaDrawingLink#49]
I'm not sure if this is a bug or an issue with the company PC, but the application doesn't work with only Rhino 8 installed. After installing Rhino 7, everything works fine, and I can then switch to Rhino 8 from the drop-down menu without any issues.

**Comment by olszewski-grzegorz** [comment]
Thanks for checking @TautvydasBakas !
I have both versions installed. In the next week I will check why it does not work when there is only 8.

**Comment by KeriTERVDeveloping** [comment]
Hello Grzegorz,

The problem is the 7 version is burned in two places in the source code:
1. Application settings
2.  And App.xaml.cs
  private string[] _rhinoFolders = new string[]
{
private string[] _rhinoFolders = new string[]
{
    //@"C:\Program Files\Rhino 7\System",
    //@"C:\Program Files\Rhino 7\Plug-ins\Grasshopper"

    @"C:\Program Files\Rhino 8\System",
    @"C:\Program Files\Rhino 8\Plug-ins\Grasshopper"
};

![image](https://github.com/user-attachments/assets/ba567fe6-ac98-4300-ac40-0d08c320e8bc)


@TautvydasBakas ,

I attached the rapid fix for the Rhino 8 version.
If would you like to try, please replace the original exe file in the installed folder.

[Grasshopper Application_For_Rhino8.zip](https://github.com/user-attachments/files/17070022/Grasshopper.Application_For_Rhino8.zip)
![image](https://github.com/user-attachments/assets/f2fce333-e500-4827-a5ca-10a25facc406)


BR 
Laci
[LinkedIn](http://www.linkedin.com/in/keresztesilaszlo/)

**Comment by olszewski-grzegorz** [comment]
Thanks @KeriTERVDeveloping for help. I appreciate your time needed to debug.

I'm currently in the middle of the trip, but as you suggested, the root cause is probably related to the app settings. There is hardcoded Rhino 7 version, which is used during first launch. As I guess, when it is not available on the user machine then the bug appear.

I will release new version in the next week, after coming back from the Tallinn AEC Hackhaton.

**Comment by olszewski-grzegorz** [comment]
New version has fixed this issue:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/releases/tag/GA_1.1

@KeriTERVDeveloping , the root cause of that bug was related to not registered comobox event in case when only Rhino 8 was installed:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/commit/6121f76f020f3a34ac86d521c1e879c15c152806?diff=split
