### ISSUE TITLE
1. Solution exception:Value cannot be null. Parameter name: obj

### ISSUE THREAD

**Issue by DSGH472** [LetsConstructIT/Grasshopper-TeklaDrawingLink#58]
I am encountering an error message: "1. Solution exception: Value cannot be null. Parameter name: obj." This error appears in several scenarios, one in the attached file picture.

I've tested the setup on both Rhino7 and Rhino8, but the issue persists in both versions. 
What might be causing this problem?

![Screenshot_2](https://github.com/user-attachments/assets/488cd998-3169-4126-ba4b-90d973832ac3)

**Comment by DSGH472** [comment]
Forget to mention that when I restart it by replacing the wire in the same position or using "Recompute Component" then it works fine.

**Comment by DSGH472** [comment]
Thank you for the quick response. I’m using Tekla 2022 and working with a
steel WQ beam drawing.

The issue seems to occur when the Grasshopper (GH) script becomes large.
Initially, there was no problem, but now it frequently appears, especially
in dimension lines and sections. Unfortunately, I can't use a loop because
some information always is missing. However, it does work if I use the
"Recompute Component" on each affected item (move view, dimension lines, or
sections). Manually recomputing each one is time-consuming.

I just checked that if I disconnect the loop then the error disappears in
all places.
Is this the right way to use a loop?
[image: image.png]

Probably this is more like a GH issue rather than a plugin issue, but it
only appears in the Tekla drawing plugins.

**Comment by olszewski-grzegorz** [comment]
I have tried to recreate your issue. I think the problem could be related to the order of execution. Based on your screenshot I don't know how you connect Loop Start and End components. The main thing is when you are sending the _Result_ input into the Loop End.

Here is the flow which stabilize the order of execution:
![image](https://github.com/user-attachments/assets/0a489c79-ae40-4b26-8039-156571225fca)
 
The Loop End component will go back to the Loop Start when it receives the _Result_ input. So you should do it after all of drawing operations. Not sure how you are doing it now, but worth to check.

Without your script, just a small subset needed to recreate the problem, I won't be able to help more. You can share it via DM on Linkedin.

**Comment by DSGH472** [comment]
The issue was likely due to an incorrect loop setup. However, I’m unsure
how to connect multiple tasks within a loop. In the attached GH file (where
I removed all unnecessary components), I’m aiming to create a section, add
dimension lines, and move views. The problem seems to lie with the stream
gate, as the "Gate" component can only operate on a single Gate Index
value.
[image: image.png]

**Comment by olszewski-grzegorz** [comment]
Hi @DSGH472 , unfortunately,  your attachement is not available on GitHub. Probably its not possible via e-mail.

Please send your script directly to me: grzegorz.olszewski123@gmail.com

**Comment by olszewski-grzegorz** [comment]
To everyone interested: we had a conversation via e-mail with author.
The problem was related to synchronizing different script flows before opening new drawing.

Quote:
I think the Null Item component should solve your problem, but it has to be used before merging results from different branches:
![image](https://github.com/user-attachments/assets/c35c2c79-1bfb-4c77-a0da-82b472cc7c67)
At the end of your branches, for their final output, check for invalid flags with the help of Null Item. Then merge those true/false, flatten them and add. If the result won't be 0, then some component before returned invalid flag, which means it's not ready yet.

I see this is too much hassle. But that's the cost of glueing grasshopper graf nature with Tekla 'single drawing at a time' limitation. I have to think about some helper 'synchronizer' component on the Drawing link side, but before that - give the above approach a try :)

Script:
https://github.com/LetsConstructIT/Grasshopper-TeklaDrawingLink/blob/main/samples/Loop%20with%20synchronization.gh

**Comment by mamo14** [comment]
Hi! I have a question related to this topic. The feature "Remove when input is empty" has been added after this bug was reported. 

This new feature allows scripts to be built with multiple scenarios e.g. if no object with name = "xxx" exists then do not output the dimensionline for these objects. This works great when handeling each drawing seperate, but gets the same error as earlier reported "1. Solution exception: Value cannot be null. Parameter name: obj." when used in a loop. I haven't found a way of using the synchronization to handle this problem.

For example multiple dimension lines might not output anything at all in some drawings since the objects does not exist. While in some drawings they should appear. Any suggestion how to handle this problem?

Let me know if you don't understand the problem and I will send you a example file!

Thanks for the amazing work!
